### ISSUE TITLE
Enhancemen: restrict CodeQL paths

### ISSUE THREAD

**Issue by SirWumpus** [ioccc-src/mkiocccentry#917]
Since enabling `CodeeQL` for one of my own projects I found it worth while to confine its work to only a subset of the repository with the use of `paths` and `paths-ignore` (avoid unnecessary scans for documentation changes, ignore example files, etc.).  For example...

```
name: "CodeQL"

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src'
      - 'jni'
    paths-ignore:
      - '**/*.md'
      - '**/*.p4'
      - '.gitignore'
      - '.gitattributes'
      - 'reference/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src'
      - 'jni'
    paths-ignore:
      - '**/*.md'
      - '**/*.p4'
      - '.gitignore'
      - '.gitattributes'
      - 'reference/**'
  schedule:
    - cron: '43 20 * * 2'
```
You might consider updating your `codeql.yml` file to apply similar restrictions.  

Related GitHub documentation https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#avoiding-unnecessary-scans-of-pull-requests

**Comment by SirWumpus** [comment]
Ugh.  It appears you can only have `paths` or `paths-ignore` defined for any single event; not both.  Go figure.

**Comment by lcn2** [comment]
> Ugh.  It appears you can only have `paths` or `paths-ignore` defined for any single event; not both.  Go figure.

Our guess is that we should use `paths` to restrict to C code and friends.  Perhaps something like:

```yml
...
    paths:
      - '*.c'
      - '*.h'
      - '**/*.c'
      - '**/*.h'
      - '**/*.y'
      - '**/*.l'
...
```

Or is it also useful for Makefiles and shell scripts?

**Comment by SirWumpus** [comment]
...
    paths:
      - '**/*.c'
      - '**/*.h'
      - '**/*.y'
      - '**/*.l'
...

> Or is it also useful for Makefiles and shell scripts?

Anything that generates or would some how impact / modified the C code.  CodeQL does not test Shell code (is that what `shellcheck` does, is it part of the test suite, CI?)  [Supported languages](https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/)

**Comment by lcn2** [comment]
> ```
> 
>     paths:
> 
>       - '**/*.c'
> 
>       - '**/*.h'
> 
>       - '**/*.y'
> 
>       - '**/*.l'
> 
> ```
> 
> 
> 
> > Or is it also useful for Makefiles and shell scripts?
> 
> 
> 
> Anything that generates or would some how impact / modified the C code. CodeQL does not test Shell code

OK.

> (is that what `shellcheck` does, is it part of the test suite, CI?)  

Yes.

> [Supported languages](https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/)

So only C stuff, not even yacc nor flex then?

**Comment by SirWumpus** [comment]
Well Yacc and Lex code generates C code, so a change to those files could impact the generated C, so I personally would include them for peace of mind.

**Comment by SirWumpus** [comment]
BTW I also found that there was a new event type supported for manual triggering actions...
```
  # Manual trigger from Actions
  workflow_dispatch:
    branches: [ "master" ]
    paths:
      - 'src'
      - 'jni'
```
Was handy to force a CodeQL workflow run after I fixed the errors.

**Comment by lcn2** [comment]
So perhaps our `codeqk.yml` should become:

```yml
name: "CodeQL"

on:
  push:
    branches: [ "master" ]
    paths:
        - '*.c'
        - '*.h'
        - '**/*.c'
        - '**/*.h'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
    paths:
        - '*.c'
        - '*.h'
        - '**/*.c'
        - '**/*.h'
  schedule:
    - cron: '18 15 * * 5'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
       # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
       
        # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
        # queries: security-extended,security-and-quality

    # Autobuild attempts to build any compiled language.
    # If this step fails, then you should remove it and run the build manually (see below)
    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    # ℹ️ Command-line programs to run using the OS shell.
    # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

    #   If the Autobuild fails above, remove it and uncomment the following three lines.
    #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.

    # - run: |
    #   echo "Run, Build Application using script"
    #   ./location_of_script_within_repo/buildscript.sh

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
```

**Comment by lcn2** [comment]
> BTW I also found that there was a new event type supported for manual triggering actions...
> 
> ```
> 
>   # Manual trigger from Actions
> 
>   workflow_dispatch:
> 
>     branches: [ "master" ]
> 
>     paths:
> 
>       - 'src'
> 
>       - 'jni'
> 
> ```
> 
> Was handy to force a CodeQL workflow run after I fixed the errors.

Where does that sit in the file?

**Comment by lcn2** [comment]
> ```
> 
>     paths:
> 
>       - '**/*.c'
> 
>       - '**/*.h'
> 
>       - '**/*.y'
> 
>       - '**/*.l'
> 
> ```

Does '**/*.x' cover top level files such as '*.x'?

**Comment by SirWumpus** [comment]
> Where does that sit in the file?

In the same section as `on: push:` ...
```
on:
  push:
    branches: [ "master" ]
    paths:
      - 'src'
      - 'jni'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src'
      - 'jni'
  # Manual trigger from Actions
  workflow_dispatch:
    branches: [ "master" ]
    paths:
      - 'src'
      - 'jni'
  schedule:
    - cron: '43 20 * * 2'
```
